/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3diu;

import java.awt.Color;

/**
 *
 * @author dilmasae
 */
public class Practica3Estela extends javax.swing.JFrame {

    /**
     * Creates new form Practica3Estela
     */
    public Practica3Estela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estelaPanel = new javax.swing.JPanel();
        estela = new practica3diu.Estela();
        autoresLabel = new javax.swing.JLabel();
        colorFondoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        colorFondo = new javax.swing.JComboBox<>();
        colorEstela = new javax.swing.JComboBox<>();
        formaEstela = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estela de Ratón");

        estelaPanel.setBackground(new java.awt.Color(255, 255, 255));
        estelaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        estela.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                estelaMouseMoved(evt);
            }
        });
        estela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estelaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout estelaLayout = new javax.swing.GroupLayout(estela);
        estela.setLayout(estelaLayout);
        estelaLayout.setHorizontalGroup(
            estelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        estelaLayout.setVerticalGroup(
            estelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout estelaPanelLayout = new javax.swing.GroupLayout(estelaPanel);
        estelaPanel.setLayout(estelaPanelLayout);
        estelaPanelLayout.setHorizontalGroup(
            estelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(estelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(estela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        estelaPanelLayout.setVerticalGroup(
            estelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
            .addGroup(estelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(estela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        autoresLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        autoresLabel.setForeground(new java.awt.Color(0, 102, 102));
        autoresLabel.setText("Edilma Alvarado Espinoza y Levy Malest Villareal");
        autoresLabel.setToolTipText("");

        colorFondoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        colorFondoLabel.setForeground(new java.awt.Color(0, 102, 102));
        colorFondoLabel.setText("Color Fondo");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Forma Estela");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Color Estela");
        jLabel4.setToolTipText("");

        colorFondo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Rosa", "Azul", "Verde", "Amarillo" }));
        colorFondo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                colorFondoItemStateChanged(evt);
            }
        });

        colorEstela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Rosa", "Azul", "Verde", "Amarillo" }));
        colorEstela.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                colorEstelaItemStateChanged(evt);
            }
        });

        formaEstela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Circulo", "Cuadrado", "Triangulo" }));
        formaEstela.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                formaEstelaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(estelaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(autoresLabel)
                        .addGap(99, 99, 99))))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(colorFondoLabel))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formaEstela, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorEstela, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorFondoLabel)
                    .addComponent(colorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(colorEstela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(formaEstela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(estelaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(autoresLabel)
                .addContainerGap())
        );

        estelaPanel.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void colorFondoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_colorFondoItemStateChanged
        // TODO add your handling code here:
        
        if(evt.getItem() instanceof String) {
            String color = (String) evt.getItem();
            
            switch(color) {
                case "Blanco":
                    estela.setColorFondo(Color.WHITE);
                    break;
                case "Rosa":
                    estela.setColorFondo(Color.PINK);
                    break;
                case "Azul":
                    estela.setColorFondo(Color.BLUE);
                    break;
                case "Verde":
                    estela.setColorFondo(Color.GREEN);
                    break;
                case "Amarillo":
                    estela.setColorFondo(Color.YELLOW);
                    break;
            }
        }

    }//GEN-LAST:event_colorFondoItemStateChanged

    private void estelaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estelaMouseMoved

        // TODO add your handling code here:
        estela.add(evt.getX(), evt.getY());
        repaint();
        
    }//GEN-LAST:event_estelaMouseMoved

    private void colorEstelaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_colorEstelaItemStateChanged
        // TODO add your handling code here:
        
        if(evt.getItem() instanceof String) {
            String color = (String) evt.getItem();
            
            switch(color) {
                case "Negro":
                    estela.setColorFigura(Color.BLACK);
                    break;
                case "Rosa":
                    estela.setColorFigura(Color.PINK);
                    break;
                case "Azul":
                    estela.setColorFigura(Color.BLUE);
                    break;
                case "Verde":
                    estela.setColorFigura(Color.GREEN);
                    break;
                case "Amarillo":
                    estela.setColorFigura(Color.YELLOW);
                    break;
            }
        }
        
    }//GEN-LAST:event_colorEstelaItemStateChanged

    private void formaEstelaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_formaEstelaItemStateChanged
        // TODO add your handling code here:
        
        if(evt.getItem() instanceof String) {
            String figura = (String) evt.getItem();
            estela.setFigura(figura);
        }
        
    }//GEN-LAST:event_formaEstelaItemStateChanged

    private void estelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estelaMouseExited
        // TODO add your handling code here:
        estela.vaciar();
        repaint();
    }//GEN-LAST:event_estelaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica3Estela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica3Estela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica3Estela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica3Estela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica3Estela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autoresLabel;
    private javax.swing.JComboBox<String> colorEstela;
    private javax.swing.JComboBox<String> colorFondo;
    private javax.swing.JLabel colorFondoLabel;
    private practica3diu.Estela estela;
    private javax.swing.JPanel estelaPanel;
    private javax.swing.JComboBox<String> formaEstela;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    
}
